CTHS/CTHS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.global_settings import MEDIA_ROOT, MEDIA_URL

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('User_app.urls')),
    path('summary/', include('Summary_app.urls')),
    path('treatment/', include('Treatment.urls')),
    path('medicine/', include('Medicine.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()

CTHS/Medicine/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from Treatment.models import Prescription
from User_app.models import Patient
# Create your models here.

class Med_supply(models.Model):
    med_sup_id = models.AutoField(_("Medical supply ID"), primary_key=True)
    sup_id = models.CharField(_("Medical Supply ID"), max_length=24, null=True)
    name = models.CharField(_("Medical supply name"), max_length=255)
    description = models.CharField(_("Medical Supply Description"), max_length=255, default="")
    amount = models.IntegerField(_("Amount left"))
    def __str__(self):
        return '%s [%s] (%s)' %(self.name, self.sup_id, self.med_sup_id)

class Drug(models.Model):
    med_sup_id = models.AutoField(_("Drug ID"), primary_key=True)
    drug_id = models.CharField(_("Drug ID"), max_length=24, null=True)
    description = models.CharField(_("Drug Description"), max_length=255, default="")
    name = models.CharField(_("Drug name"), max_length=255)
    amount = models.IntegerField(_("Amount left"))
    patient = models.ManyToManyField(Patient, verbose_name=_("Allergic Drug(s)"))
    def __str__(self):
        return '%s [%s] (%s)' %(self.name, self.drug_id, self.med_sup_id)

class Dispense(models.Model):
    amount =  models.IntegerField(_("Amount"))
    DISPENSE_TYPE_CHOICE = [
        ('D', 'ยา'),
        ('M', 'เวชภัณฑ์')
    ]
    type = models.CharField(_("Dispense type"), max_length=1, choices=DISPENSE_TYPE_CHOICE)
    prescription_id = models.ForeignKey(Prescription, verbose_name=_("Prescription ID"), on_delete=models.CASCADE)
    dis_med_id = models.ForeignKey(Med_supply, verbose_name=_("Dispense ID"), on_delete=models.CASCADE, null=True, blank=True)
    dis_drug_id = models.ForeignKey(Drug, verbose_name=_("Dispense ID"), on_delete=models.CASCADE, null=True, blank=True)
    def __str__(self):
        return 'Prescription ID: %s [จำนวน : %s] (%s)' %(self.prescription_id.id, self.amount, self.type)

CTHS/Treatment/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from User_app.models import Patient, Nurse, Doctor


# Create your models here.
SYMPTOM_TYPE = [
        ('non_form', 'ทั่วไป'),
        ('skin', 'ผิวหนัง'),
        ('accident', 'อุบัติเหตุ'),
        ('con_accident', 'อุบัติเหตุต่อเนื่อง'),
        ('eyes', 'ดวงตา'),
        ('fever', 'อาการไข้'),
        ('diarrhea', 'ท้องเสีย/ปวดท้อง'),
        ('pain', 'อาการปวดนอกเหนือ')
]
class Icd_10(models.Model):
    code = models.CharField(_("code"), max_length=25, unique=True)
    detail = models.CharField(_("detail"), max_length=255)
    symptom_type = models.CharField(_("symptom_type"), max_length=12, choices=SYMPTOM_TYPE)
    def __str__(self):
        return '%s (%s)' %(self.code, self.symptom_type)

class Treatment(models.Model):
    cn = models.AutoField(_("Clinic number"), primary_key=True)
    weight = models.FloatField(_("Weight"))
    Height = models.FloatField(_("Height"))
    bp = models.IntegerField(_("Blood pressures"))
    pr = models.IntegerField(_("Pulse rates"))
    temp = models.FloatField(_("Temperatures"))
    rr = models.IntegerField(_("Respiratory rates"))
    bmi = models.FloatField(_("BMI"))
    o2_sat = models.IntegerField(_("Oxygen saturation"))
    med_cer = models.BooleanField(_("Medical certificate"))
    # follow_up = models.DateField(_("Follow up ?"), auto_now=False, auto_now_add=False)
    PATIENT_CONDITION_CHOICE = [
        ('SC', 'มาด้วยตนเอง'),
        ('AB', 'รถพยาบาล'),
        ('ST', 'เปลนอน')
    ] 
    patient_condition = models.CharField(_("Patient Condition"), max_length=2, choices=PATIENT_CONDITION_CHOICE, default='SC')
    # current_history = models.CharField(_("Current History"), max_length=255)
    create_date = models.DateField(_(""), auto_now=True)
    
    def __str__(self):
        return "cn : "+str(self.cn) + ' ของ '+self.patient_p_id.fname
    

    def bmi(self):
        return  self.weight / self.Height**2
    bmi = property(bmi)
    
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_("Creator user"), on_delete=models.CASCADE) #change from o2o to foriegnfield
    patient_p_id = models.ForeignKey(Patient, verbose_name=_("PatientID"), on_delete=models.CASCADE)

class Diagnosis(models.Model):
    icd_10 = models.ManyToManyField(Icd_10, verbose_name=_("icd_10s"))
    diagnosis_detail = models.CharField(_("คำวินิฉัย"), max_length=255, blank=True)
    advice = models.CharField(_("คำเเนะนำ"), max_length=255, blank=True)
    doctor_id = models.ForeignKey(Doctor, verbose_name=_("Diagnos Doctor"), on_delete=models.CASCADE)
    follow_up = models.DateField(_("วันนัด"), null=True)
    follow_up_for = models.CharField(_("เพื่อ"), max_length=100, blank=True)
    treatment = models.OneToOneField(Treatment, verbose_name=_("Treatment ID"), on_delete=models.CASCADE, null=True)
    def __str__(self):
        return '%s (%s)' %(self.doctor_id, self.treatment.cn)

class Symptom(models.Model):
    treatment = models.OneToOneField(Treatment, verbose_name=_("Treatment"), on_delete=models.CASCADE)
    symptom_type = models.CharField(_("symptom_type"), max_length=12, choices=SYMPTOM_TYPE, null=True)
    def __str__(self):
        return 'ID : %s (%s)' %(self.id, self.symptom_type)

class Prescription(models.Model):
    detail = models.CharField(_("Prescription detail"), max_length=255, blank=True)
    doctor_id = models.ForeignKey(Doctor, verbose_name=_("Creator ID"), on_delete=models.CASCADE, null=True)
    treatment_cn = models.OneToOneField(Treatment, verbose_name=_("Treatment Clinic number"), on_delete=models.CASCADE)
    PRESCRIPTION_STATUS_CHOICE = [
        ('C', 'จ่ายยาแล้ว'),
        ('W', 'รอการจ่ายยา')
    ]
    status = models.CharField(_("Prescription Status"), max_length=1, choices=PRESCRIPTION_STATUS_CHOICE, default="W")
    nurse_id = models.ForeignKey(Nurse, verbose_name=_("พยาบาลผู้จ่ายยา"), on_delete=models.CASCADE, null=True)


class Non_Form_Symptom(models.Model):
    symptom = models.OneToOneField(Symptom, verbose_name=_("Symptom ID"), on_delete=models.CASCADE)
    important_symptom = models.CharField(_("อาการสำคัญ"),max_length=255)
    current_history = models.CharField(_("ประวัติปัจจุบัน"),max_length=255)

class Rash_Symptom(models.Model):
    symptom = models.OneToOneField(Symptom, verbose_name=_("Symptom ID"), on_delete=models.CASCADE)
    rash_area = models.CharField(_("ผื่นบริเวณ"), max_length=255)
    rash_date = models.IntegerField(_("เป็นมานาน (วัน)"), default=1)
    itch = models.BooleanField(_("คัน"), default=False)
    pain = models.BooleanField(_("ปวด"), default=False)
    sting = models.BooleanField(_("เเสบ"), default=False)
    fever = models.BooleanField(_("ไข้"), default=False)
    swell = models.BooleanField(_("บวม"), default=False)
    rash_detail = models.CharField(_("สัมผัสโดน"), max_length=255)
    pe = models.CharField(_("PE"), max_length=255)

class Wound_Symptom(models.Model):
    symptom = models.OneToOneField(Symptom, verbose_name=_("Symptom ID"), on_delete=models.CASCADE)
    emergency = models.BooleanField(_('ผู้ป่วยฉุกเฉิน'),default=False)
    insurance = models.BooleanField(_("เบิกประกันอุบัติเหตุ"), default=False)
    is_safety = models.BooleanField(_("สวมหมวกันน็อค/คาดเข็มขัด"), default=False)
    wound_area = models.CharField(_("บาดเเผลบริเวณ"), max_length=255)
    wound_date = models.DateField(_("วันที่เกิดเหตุ"))
    wound_locale = models.CharField(_("สถานที่เกิดเหตุ"), max_length=255)
    is_treat_before = models.BooleanField(_("เคยเข้ารับการรักมาเเล้ว"), default=False)
    treatment_before_detail = models.CharField(_("ที่"), max_length=255, blank=True)
    time = models.TimeField(_("เวลา"), blank=True)


class Lesion(models.Model):
    wound_symptom = models.ForeignKey(Wound_Symptom, on_delete=models.CASCADE)
    AREA_TYPE_CHOICE = [
        ('1', 'ถลอก'),
        ('2', 'ฉีกขาด'),
        ('3', 'จากของมีคม'),
        ('4', 'อื่นๆ'),
    ]
    lesion_type = models.CharField(_("บาดแผล"), max_length=1, choices=AREA_TYPE_CHOICE)
    lesion_area = models.CharField(_("บริเวณ"), max_length=100)
    lesion_x = models.IntegerField(_("กว้าง"))
    lesion_y = models.IntegerField(_("ยาว"))

class Con_Wound_Symptom(models.Model):
    symptom = models.OneToOneField(Symptom, verbose_name=_("Symptom ID"), on_delete=models.CASCADE, null=True)
    LESION = [
        ('1','เเย่ลง'),
        ('2','เท่าเดิม'),
        ('3','ดีขึ้น')
    ]
    insurance = models.BooleanField(_("ผู้ป่วยเบิกประกัน"), default=False)
    detail = models.CharField(_("ลักษณะบาดเเผล"), max_length=1 , choices=LESION, default=LESION[1][0])
    advice = models.CharField(_("คำเเนะนำ"), max_length=100,blank=True)
    more = models.CharField(_("เพิ่มเติ่ม"), max_length=100)

    
class Eye_Symptom(models.Model):
    symptom = models.OneToOneField(Symptom, verbose_name=_("Symptom ID"), on_delete=models.CASCADE)
    left = models.BooleanField(_("ตาซ้าย"), default=False)
    right = models.BooleanField(_("ตาขวา"), default=False)
    pain = models.BooleanField(_("ปวดตา"), default=False)
    irritation = models.BooleanField(_("เคืองตา"), default=False)
    itch = models.BooleanField(_("คันตา"), default=False)
    conjunctivitis = models.BooleanField(_("ตาเเดง"), default=False)
    sore = models.BooleanField(_("เจ็บหนังตา"), default=False)
    swoll = models.BooleanField(_("หนังตาบวม"), default=False)
    tear = models.BooleanField(_("น้ำตาไหล"), default=False)
    blurred = models.BooleanField(_("ตาพร่ามัว"), default=False)
    gum = models.BooleanField(_("ขี้ตาเยอะ"), default=False)
    purulent = models.BooleanField(_("ขี้ตาเป็นหนอง"), default=False)
    matter = models.BooleanField(_("สิ่งเเปลกปลอมเข้าดวงตา"), default=False)
    check_up = models.CharField(_("ตรวจร่างกาย"), max_length=255, blank=True)

class Fever_Symptom(models.Model):
    symptom = models.OneToOneField(Symptom, verbose_name=_("Symptom ID"), on_delete=models.CASCADE)
    fever = models.BooleanField(_("ไข้"))
    cough = models.BooleanField(_("ไอ"))
    phlegm = models.BooleanField(_("เสมหะ"))
    snot = models.BooleanField(_("น้ำมูก"))
    headache = models.BooleanField(_("ปวดศีรษะ"))
    stuffy = models.BooleanField(_("คัดจมูก"))
    food_bored = models.BooleanField(_("เบื่ออาหาร"))
    body_aches = models.BooleanField(_("ปวดเมื่อยตามตัว"))
    sore_throat = models.BooleanField(_("เจ็บคอ"))
    eye_itch = models.BooleanField(_("คันตา"))

    injected_pharynx = models.BooleanField(_("Injected pharynx"))
    exudates = models.BooleanField(_("Exudates"))
    lungs = models.BooleanField(_("Lungs : Clear"))
    more = models.CharField(_("เพิ่มเติ่ม"), max_length=255, blank=True)

class Diarrhea_Symptom(models.Model):
    symptom = models.OneToOneField(Symptom, verbose_name=_("Symptom ID"), on_delete=models.CASCADE)
    diarrhea_amount = models.IntegerField(_("จำนวนครั้งในการถ่าย"), default=0)
    diarrhea_detail = models.CharField(_("อุจจาระลักษณะ"), max_length=255 , blank=True, default="")

    stomachache = models.CharField(_("ลักษณะการปวดท้อง"), max_length=255, blank=True, default='')
    vomit = models.BooleanField(_("คลื่นไส้/อาเจียน"), default=False)
    flux_stool = models.BooleanField(_("อุจาระมีมูลเลือด"), default=False)
    fever = models.BooleanField(_("ไข้"), default=False)
    
    bowel_sound = models.CharField(_("bowel sound"), max_length=255, blank=True, default='')
    current_history = models.CharField(_("ประวัติปัจจุบัน"), max_length=255, blank=True, default='')

class Pain_Symptom(models.Model):
    symptom = models.OneToOneField(Symptom, verbose_name=_("Symptom ID"), on_delete=models.CASCADE)
    bodyache_area = models.CharField(_("ปวดบริเวณ"), max_length=255)
    bodyache_date = models.IntegerField(_("เป็นมานาน (วัน)"))
    pain_score = models.IntegerField(_("Pain score"))
    ache_detail = models.CharField(_("ลักษณะการปวด"), max_length=255)

CTHS/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Clinic Treatment History System</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css'%}">
    <link rel="stylesheet" href="{% static 'css/signincss.css'%}">
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>

    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    {% block scripts %}
    {% endblock %}
    {% block style %}
    {% endblock %}
    <style>
        .bg-light {
            background-color: #bde4e2 !important;
        }

        .disable {
            pointer-events: none;
            cursor: default;
            color: gray;
        }
    </style>
    


</head>


<body>

    <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="#">Clinic Treatment History</a>
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarsExample01"
            aria-controls="navbarsExample01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-collapse collapse" id="navbarsExample01" style="">
            <ul class="navbar-nav mr-auto">
                
                <li class="nav-item">
                    <a class="nav-link" href="{%  url 'my_logout' %}">SignOut</a>
                </li>
            </ul>
        </div>
    </nav>
    {% if user.is_authenticated %}
    {% include 'sidebar.html' %}
    {% endif %}

    {% block content %}
    {% endblock %}


    <footer class="footer">
        <div class="container">
            <span class="text-muted">
                {% block footer %}
                {% endblock %}
            </span>
        </div>
    </footer>
    
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
        feather.replace()

        
    </script>


</body>

</html>

CTHS/templates/messages.html
{% if messages %}
{% for message in messages %}
<div class="alert alert-{% if message.tags == 'error' %}danger {% else %}{{message.tags}} {% endif %}
                alert-dismissible fade show" role="alert">
    <strong>{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}</strong>
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}

{% endif %}

CTHS/templates/sidebar.html
<div class="container-fluid">
  <div class="row">
    <nav class="col-md-2 d-none d-md-block sidebar">
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
         
            <a class="nav-link active" href="{% url 'index' %}">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
              Home <span class="sr-only"></span>
            </a>
          </li>
          
          
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home_patient' %}">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
              Patients
            </a>
          </li>
          {% if perms.Treatment.add_treatment %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home_treatment' %}">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline></svg>
              Treatments
            </a>
          </li>
         {% endif %}
         {% if perms.Treatment.view_diagnosis %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home_diagnosis' %}">
              <svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="css-i6dzq1"><polyline points="22 12 18 12 15 21 9 3 6 12 2 12"></polyline></svg>
              Diagnosis
            </a>
          {% endif %}
          {% if perms.Medicine.view_drug %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home_medicine' %}" >
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-layers"><polygon points="12 2 2 7 12 12 22 7 12 2"></polygon><polyline points="2 17 12 22 22 17"></polyline><polyline points="2 12 12 17 22 12"></polyline></svg>
              Medicine
            </a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'dashboard' %}">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bar-chart-2"><line x1="18" y1="20" x2="18" y2="10"></line><line x1="12" y1="20" x2="12" y2="4"></line><line x1="6" y1="20" x2="6" y2="14"></line></svg>
              Reports
            </a>
          </li>
          {% if perms.auth.add_logentry %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home_admin' %}" >
              <svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="css-i6dzq1"><circle cx="12" cy="12" r="10"></circle><line x1="14.31" y1="8" x2="20.05" y2="17.94"></line><line x1="9.69" y1="8" x2="21.17" y2="8"></line><line x1="7.38" y1="12" x2="13.12" y2="2.06"></line><line x1="9.69" y1="16" x2="3.95" y2="6.06"></line><line x1="14.31" y1="16" x2="2.83" y2="16"></line><line x1="16.62" y1="12" x2="10.88" y2="21.94"></line></svg>
              Administor
            </a>
          </li>
          {% endif %}
        </ul>

        <!-- <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Saved reports</span>
          <a class="d-flex align-items-center text-muted" href="#">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus-circle"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="16"></line><line x1="8" y1="12" x2="16" y2="12"></line></svg>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
              Current month
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
              Last quarter
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
              Social engagement
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
              Year-end sale
            </a>
          </li>
        </ul> -->
      </div>
    </nav>